using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiniTwitch.EventSub.CodeGen;

[Generator]
internal class EventSubRouterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var structProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "MiniTwitch.EventSub.Internal.EventSubEventAttribute",
                predicate: (node, _) => node is StructDeclarationSyntax,
                transform: (ctx, _) => (StructDeclarationSyntax)ctx.TargetNode)
            .Collect();

        context.RegisterSourceOutput(structProvider, static (spc, structs) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine($$"""
                // <auto-generated />
                #nullable enable
                using System;
                using System.Text.Json;
                using System.Threading.Tasks;
                using MiniTwitch.EventSub.Models;
                using MiniTwitch.EventSub.Internal.Parsing;
                using MiniTwitch.Common.Extensions;

                namespace MiniTwitch.EventSub.Generated;

                internal static partial class EventSubGeneratedRouter
                {
                    public static bool TryDispatch(ReadOnlyMemory<byte> message, object handlerState, out Exception? error)
                    {
                        error = null;
                        EventSubscription sub = new(message.GetChild("subscription"u8));

                        // {{structs.Length}} structs
                        switch (sub.Type)
                        {
                """);

            foreach (var decl in structs)
            {
                var attr = decl.AttributeLists
                    .SelectMany(a => a.Attributes)
                    .First(a => a.Name.ToString().Contains("EventSubEvent"));

                var type = attr.ArgumentList?.Arguments[0].ToString().Trim('"') ?? throw new Exception("Shouldnt be null");
                var version = attr.ArgumentList?.Arguments[1].ToString().Trim('"') ?? throw new Exception("Shouldnt be null");
                var structName = decl.Identifier.ValueText;
                sb.AppendLine($$"""
                            // {{structName}}
                            case "{{type}}" when sub.Version == "{{version}}":
                            {
                                try
                                {
                                    var {{structName}}_Handler = (Func<EventSubMessage<{{structName}}>, ValueTask>)handlerState;
                                    EventSubMessage<{{structName}}> {{structName}}_Message = new()
                                    {
                                        Subscription = sub,
                                        Event = new {{structName}}(message.GetChild("event"u8))
                                    };

                                    {{structName}}_Handler({{structName}}_Message).StepOver();
                                    return true;
                                }
                                catch (Exception e)
                                {
                                    error = e;
                                    return false;
                                }
                            }
                """);
            }

            sb.AppendLine("""
                        default:
                            error = new InvalidOperationException("Unknown subscription type");
                            return false;
                    } // Switch
                } // TryDispatch
            """);

            sb.AppendLine("} // Class");

            spc.AddSource("EventSubGeneratedRouter.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }
}
