using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MiniTwitch.EventSub.CodeGen;

[Generator]
public class EventSubLazyStructGenerator : IIncrementalGenerator
{
    readonly List<string> _propNames = [];
    readonly Dictionary<string, List<StructDeclarationSyntax>> _nestedChildren = [];

    readonly struct TypeRule(string getMethod, string getArrayMethod, bool hasIntern)
    {
        public readonly string GetMethod = getMethod;
        public readonly string GetArrayMethod = getArrayMethod;
        public readonly bool HasIntern = hasIntern;
    }

    static readonly Dictionary<string, TypeRule> _typeRules = new()
    {
        ["string"] = new("GetString", "GetStringArray", true),
        ["int"] = new("GetInt", "GetIntArray", false),
        ["bool"] = new("GetBool", "", false),
        ["long"] = new("GetLong", "GetLongArray", false),
        [nameof(Guid)] = new("GetGuid", "", false),
        [nameof(DateTimeOffset)] = new("GetTime", "", false),

    };

    static string GetQualifiedName(StructDeclarationSyntax decl)
    {
        var name = decl.Identifier.ValueText;
        if (decl.Parent is StructDeclarationSyntax parent)
            return $"{GetQualifiedName(parent)}.{name}";
        return name;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var eventStructProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "MiniTwitch.EventSub.Internal.EventSubEventAttribute",
                predicate: (node, _) => node is StructDeclarationSyntax,
                transform: (ctx, _) => (StructDeclarationSyntax)ctx.TargetNode)
            .Collect();
        var eventPropStructProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "MiniTwitch.EventSub.Internal.EventPropertyAttribute",
                predicate: (node, _) => node is StructDeclarationSyntax,
                transform: (ctx, _) => (StructDeclarationSyntax)ctx.TargetNode)
            .Collect();


        context.RegisterSourceOutput(eventPropStructProvider, (spc, structs) =>
        {
            _propNames.Clear();
            _nestedChildren.Clear();

            foreach (var decl in structs)
            {
                var structName = decl.Identifier.ValueText;
                _propNames.Add(structName);

                if (decl.Parent is StructDeclarationSyntax parent)
                {
                    var qualifiedName = GetQualifiedName(decl);
                    _propNames.Add(qualifiedName);

                    var parentName = parent.Identifier.ValueText;
                    if (!_nestedChildren.ContainsKey(parentName))
                    {
                        _nestedChildren[parentName] = [];
                    }

                    _nestedChildren[parentName].Add(decl);
                }
            }

            foreach (var decl in structs)
            {
                if (decl.Parent is StructDeclarationSyntax)
                {
                    continue;
                }

                var sb = new StringBuilder();
                var structName = decl.Identifier.ValueText;
                GenerateFile(sb, decl, "");
                spc.AddSource($"{structName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }

        });

        context.RegisterSourceOutput(eventStructProvider, (spc, structs) =>
        {
            foreach (var decl in structs)
            {
                var sb = new StringBuilder();
                var structName = decl.Identifier.ValueText;
                GenerateFile(sb, decl, "");
                spc.AddSource($"{structName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }

        });
    }

    void GenerateFile(StringBuilder sb, StructDeclarationSyntax decl, string indent)
    {
        var structName = decl.Identifier.ValueText;
        sb.AppendLine($$"""
            // <auto-generated />
            #nullable enable
            using System;
            using System.Text.Json;
            using System.Threading.Tasks;
            using MiniTwitch.EventSub.Models;
            using MiniTwitch.EventSub.Internal;
            using System.Linq;
            using MiniTwitch.EventSub.Internal.Parsing;

            namespace MiniTwitch.EventSub.Models;

            """);

        GenerateStructBody(sb, decl, indent);
    }

    void GenerateStructBody(StringBuilder sb, StructDeclarationSyntax decl, string indent)
    {
        var structName = decl.Identifier.ValueText;
        sb.AppendLine($"{indent}public partial struct {structName}(ReadOnlyMemory<byte> slice)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    internal bool IsInitialized => !slice.IsEmpty;");

        foreach (var prop in decl.Members.OfType<PropertyDeclarationSyntax>())
        {
            AddProp(sb, prop, indent);
        }

        if (_nestedChildren.TryGetValue(structName, out var children))
        {
            foreach (var childDecl in children)
            {
                GenerateStructBody(sb, childDecl, indent + "    ");
            }
        }

        sb.AppendLine($"{indent}}} // Struct");
    }

    void AddProp(StringBuilder sb, PropertyDeclarationSyntax prop, string indent)
    {
        var propType = prop.Type.ToString();
        var propName = prop.Identifier.ValueText;
        var jsonName = GetJsonPropertyName(prop) ?? JsonSnakeCaseLowerNamingPolicy.Instance.ConvertName(propName);
        var shouldIntern = HasInternAttribute(prop);

        bool isNullable = propType.EndsWith("?");
        var baseType = isNullable ? propType.Substring(0, propType.Length - 1) : propType;
        bool isArray = baseType.EndsWith("[]");
        var elementType = isArray ? baseType.Substring(0, baseType.Length - 2) : baseType;

        sb.Append($"{indent}    public partial {propType} {propName} => ");

        if (_propNames.Contains(elementType))
        {
            GenerateChild(sb, elementType, isNullable, isArray, jsonName);
        }
        else if (_typeRules.TryGetValue(elementType, out var rule))
        {
            GenerateFromRule(sb, rule, elementType, isNullable, isArray, jsonName, shouldIntern);
        }
    }

    static void GenerateFromRule(StringBuilder sb, TypeRule rule, string elementType, bool isNullable, bool isArray, string jsonName, bool shouldIntern)
    {
        if (isArray)
        {
            if (string.IsNullOrEmpty(rule.GetArrayMethod))
                return;

            var intern = rule.HasIntern ? $", intern: {(shouldIntern ? "true" : "false")}" : "";
            sb.Append($"field ??= slice.{rule.GetArrayMethod}(\"{jsonName}\"u8{intern})");
            sb.AppendLine(isNullable ? ";" : " ?? [];");
            return;
        }

        if (rule.HasIntern)
        {
            sb.Append($"field ??= slice.{rule.GetMethod}(\"{jsonName}\"u8, intern: {(shouldIntern ? "true" : "false")})");
            sb.AppendLine(isNullable ? ";" : "!;");
            return;
        }

        if (isNullable)
        {
            sb.AppendLine($"field ??= slice.{rule.GetMethod}(\"{jsonName}\"u8);");
        }
        else
        {
            sb.AppendLine($"field == default({elementType}) ? field = slice.{rule.GetMethod}(\"{jsonName}\"u8).GetValueOrDefault() : field;");
        }
    }

    static void GenerateChild(StringBuilder sb, string childType, bool isNullable, bool isArray, string jsonName)
    {
        if (isArray)
        {
            var source = $"slice.GetChildrenArray(\"{jsonName}\"u8)";
            var transform = $".Select(static c => new {childType}(c)).ToArray()";
            sb.AppendLine(isNullable
                ? $"field ??= {source}?{transform};"
                : $"field ??= ({source} ?? []){transform};");
            return;
        }

        sb.AppendLine(isNullable
            ? $"field ??= new(slice.GetChild(\"{jsonName}\"u8));"
            : $"!field.IsInitialized ? new(slice.GetChild(\"{jsonName}\"u8)) : field;");
    }

    static string? GetJsonPropertyName(PropertyDeclarationSyntax prop) =>
        prop.AttributeLists
            .SelectMany(a => a.Attributes)
            .FirstOrDefault(a => a.Name.ToString().Contains("JsonPropertyName"))?
            .ArgumentList?.Arguments[0].ToString().Trim('"');

    static bool HasInternAttribute(PropertyDeclarationSyntax prop) =>
        prop.AttributeLists
            .SelectMany(a => a.Attributes)
            .Any(a => a.Name.ToString().Contains("Intern"));
}

